// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2021-07-05T20:10:03.890334100
package tech.kzen.project.client.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectJsModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
