// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2022-08-18T19:03:24.033382500
package tech.kzen.project.server.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectJvmModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
