// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2021-07-05T20:10:03.892328700
package tech.kzen.project.server.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectJvmModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
