// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2021-05-05T12:13:15.770565600
package tech.kzen.project.server.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectJvmModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
