// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2021-07-05T20:10:03.870878300
package tech.kzen.project.common.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectCommonModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
