// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2021-05-05T12:13:15.760592500
package tech.kzen.project.common.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectCommonModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
