// **DO NOT EDIT, CHANGES WILL BE LOST** - automatically generated by ModuleReflectionGenerator at 2023-04-11T23:17:28.416472100
package tech.kzen.project.common.codegen

import tech.kzen.lib.common.reflect.ReflectionRegistry
import tech.kzen.lib.common.reflect.ModuleReflection


@Suppress("UNCHECKED_CAST")
object KzenProjectCommonModule: ModuleReflection {
    override fun register(reflectionRegistry: ReflectionRegistry) {

    }
}
